//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualProgrammingFinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan EntryTime { get; set; }
        public Nullable<System.TimeSpan> ExitTime { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
