//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualProgrammingFinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> lng { get; set; }
        public Nullable<float> northeast_lat { get; set; }
        public Nullable<float> northeast_lng { get; set; }
        public Nullable<float> southwest_lat { get; set; }
        public Nullable<float> southwest_lng { get; set; }
    }
}
